import NavBar from '@/components/navbar.js'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import StoreProvider from '@/components/StoreProvider'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavBar />
          <main>
          {children}
          </main>
          <Footer />
        </StoreProvider>

      </body>
    </html>
  )
}
